# permissions for end users to edit dtms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dtm-editor-role
rules:
- apiGroups:
  - app.dtm.hub
  resources:
  - dtms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.dtm.hub
  resources:
  - dtms/status
  verbs:
  - get
