# permissions for end users to view dtms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dtm-viewer-role
rules:
- apiGroups:
  - app.dtm.hub
  resources:
  - dtms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.dtm.hub
  resources:
  - dtms/status
  verbs:
  - get
