
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.dtm.hub
  resources:
  - dtms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.dtm.hub
  resources:
  - dtms/finalizers
  verbs:
  - update
- apiGroups:
  - app.dtm.hub
  resources:
  - dtms/status
  verbs:
  - get
  - patch
  - update
